// Columnas del libro de remuneraciones prorrateado, en el orden de libro_rem_dist_excel.php
// (aplicativo antiguo libro_rem_dis). Compartido entre servidor y cliente (sin dependencias de Node).

/** Columnas fijas del inicio (SOCIEDAD … PORCENTAJE PRORRATEO). */
export const COLUMNAS_INICIO = [
  { clave: "sociedad", titulo: "SOCIEDAD" },
  { clave: "cc", titulo: "CENTRO COSTO" },
  { clave: "nombre_completo", titulo: "NOMBRE COMPLETO" },
  { clave: "rut", titulo: "RUT" },
  { clave: "np", titulo: "NP" },
  { clave: "cargo", titulo: "CARGO" },
  { clave: "tipo_contrato", titulo: "TIPO CONTRATO" },
  { clave: "fecha_ingreso", titulo: "FECHA INGRESO" },
  { clave: "fecha_estimada_termino", titulo: "FECHA ESTIMADA TERMINO" },
  { clave: "fecha_retiro", titulo: "FECHA RETIRO" },
  { clave: "dias", titulo: "DIAS TRABAJADOS" },
  { clave: "porcentaje", titulo: "PORCENTAJE PRORRATEO" },
] as const;

/** Columnas fijas del final. */
export const COLUMNAS_FIN = [
  { clave: "nombre_clasificacion_gasto", titulo: "CLASIFICACION DE GASTO" },
  { clave: "ames", titulo: "AMES" },
  { clave: "planta", titulo: "PLANTA" },
] as const;

export interface ConceptoProrrateado {
  /** Columna de flesan_rrhh.libro_rem_nuevo_g2 (y nombre del concepto en el original). */
  clave: string;
  titulo: string;
  /** Cantidad de horas: texto con coma decimal, vacío = 0 (el original la convertía así). */
  horas?: true;
}

/**
 * Conceptos que el Excel muestra si alguna fila tiene un valor distinto de cero, con los títulos
 * del original (incluido «COTIZACION SALud»). El original también listaba las horas extra de 42
 * horas (mi56), pero su consulta no las traía y nunca salían; y su consulta calculaba otras 34
 * columnas que el Excel nunca mostraba: aquí no se piden.
 */
export const CONCEPTOS: ConceptoProrrateado[] = [
  { clave: "costo_empresa", titulo: "COSTO EMPRESA" },
  { clave: "sueldo_base", titulo: "SUELDO BASE" },
  { clave: "gratificacion", titulo: "GRATIFICACION" },
  { clave: "colacion", titulo: "COLACION" },
  { clave: "movilizacion", titulo: "MOVILIZACION" },
  { clave: "bono_uno", titulo: "BONO UNO" },
  { clave: "aguinaldo", titulo: "AGUINALDO" },
  { clave: "bono", titulo: "BONO" },
  { clave: "bono_anual", titulo: "BONO ANUAL" },
  { clave: "bono_produccion", titulo: "BONO PRODUCCION" },
  { clave: "bono_responsabilidad", titulo: "BONO RESPONSABILIDAD" },
  { clave: "bono_zona", titulo: "BONO ZONA" },
  { clave: "bono_sala_cuna", titulo: "BONO SAL_CUNA" },
  { clave: "comision_ventas", titulo: "COMISION VENTAS" },
  { clave: "semana_corrida", titulo: "SEMANA CORRIDA" },
  { clave: "cantidad_horas_extra", titulo: "CANTIDAD HORAS EXTRA", horas: true },
  { clave: "horas_extra_50_prociento", titulo: "HORAS EXTRA 50 PORCIENTO" },
  { clave: "asignacion_traslacion", titulo: "ASIGNACION TRASLACION" },
  { clave: "viatico", titulo: "VIATICO" },
  { clave: "viatico_anticipado", titulo: "VIATICO ANTICIPADO" },
  { clave: "adicional_colacion", titulo: "ADICIONAL COLACION" },
  { clave: "adicional_movilizacion", titulo: "ADICIONAL MOVILIZACION" },
  { clave: "ajuste_liquidacion_n_imp", titulo: "AJUSTE LIQUIDACION N IMPUESTO" },
  { clave: "asignacion_telefono", titulo: "ASIGNACION TELEFONO" },
  { clave: "vacaciones_proporcionales", titulo: "VACACIONES PROPORCIONALES" },
  { clave: "mes_aviso", titulo: "MES DE AVISO" },
  { clave: "indemnizacion_legal", titulo: "INDEMNIZACION LEGAL" },
  { clave: "indemnizacion_tiempo_servicio", titulo: "INDEMNIZACION TIEMPO DE SERVICIO" },
  { clave: "indemnizacion_voluntaria", titulo: "INDEMNIZACION VOLUNTARIA" },
  { clave: "sobregiro", titulo: "SOBREGIRO" },
  { clave: "asignacio_familiar", titulo: "ASIGNACION FAMILIAR" },
  { clave: "cotizacion_afp", titulo: "COTIZACION AFP" },
  { clave: "ahorro_voluntario", titulo: "AHORRO VOLUNTARIO" },
  { clave: "apv_reg_a", titulo: "APV REG A" },
  { clave: "apv_reg_b", titulo: "APV REG B" },
  { clave: "cotizacion_adiciona_salud", titulo: "COTIZACION ADICIONAL SALUD" },
  { clave: "cotizacion_salud", titulo: "COTIZACION SALud" },
  { clave: "seguro_cesantia", titulo: "SEGURO CESANTIA" },
  { clave: "impuesto_renta", titulo: "IMPUESTO A LA RENTA" },
  { clave: "anticipo", titulo: "ANTICIPO" },
  { clave: "anticipo_aguinaldo", titulo: "ANTICIPO AGUINALDO" },
  { clave: "retencion_judicial", titulo: "RETENCION JUDICIAL" },
  { clave: "convenio_falp", titulo: "CONVENIO FALP" },
  { clave: "full_ahorro_caja", titulo: "FULL AHORRO CAJA" },
  { clave: "pmo_solidario_ley_21252", titulo: "PMO SOLIDARIO LEY 21.252" },
  { clave: "seguro_dental", titulo: "SEGURO DENTAL" },
  { clave: "seguro_salud", titulo: "SEGURO SALUD" },
  { clave: "seguro_ccaf", titulo: "SEGURO CCAF" },
  { clave: "seguro_chilena_consolidada", titulo: "SEGURO CHILENA CONSOLIDADA" },
  { clave: "seguro_vida_camara", titulo: "SEGURO DE SALUD" },
  { clave: "costo_seguro_com", titulo: "COSTO SEGURO COMPLEMENTARIO" },
  { clave: "sobregiro_mes_anterior", titulo: "SOBREGIRO MES ANTERIOR" },
  { clave: "descuento_alojamiento", titulo: "DESCUENTO ALOJAMIENTO" },
  { clave: "descuento_fxr", titulo: "DESCUENTO FxR" },
  { clave: "dcto_bienestar", titulo: "DESCUENTO BROLLY" },
  { clave: "descuento_por_ajuste", titulo: "DESCUENTO POR AJUSTE" },
  { clave: "ajuste_finiquito", titulo: "INDEMNNIZACIÓN CTP" },
  { clave: "prestamo_ccaf_los_andes", titulo: "PRESTAMO CCAF LOS ANDES" },
  { clave: "descuento_casona", titulo: "DESCUENTO CASONA" },
  { clave: "anticipo_finiquito", titulo: "ANTICIPO FINIQUITO" },
  { clave: "prestamo_empresa", titulo: "PRÉSTAMO EMPRESA" },
  { clave: "descuento_sobregiro", titulo: "DESCUENTO SOBREGIRO" },
  { clave: "desgaste_herramienta", titulo: "DESGASTE HERRAMIENTA" },
  { clave: "ausencia", titulo: "AUSENCIA" },
  { clave: "licencia_medica", titulo: "LICENCIA MEDICA" },
  { clave: "liquido_pago", titulo: "LIQUIDO A PAGO" },
  { clave: "aporte_afc", titulo: "APORTE AFC" },
  { clave: "descuento_aporte_afc", titulo: "DESCUENTO APORTE AFC" },
  { clave: "desc_prestamo_empresa", titulo: "DESCUENTO PRESTAMO EMPRESA" },
  { clave: "mutual", titulo: "MUTUAL" },
  { clave: "sis", titulo: "SIS" },
  { clave: "imponible", titulo: "IMPONIBLE" },
  { clave: "bono_puntualidad", titulo: "BONO PUNTUALIDAD" },
  { clave: "trato", titulo: "TRATO" },
  { clave: "covid_19", titulo: "SUSP. REM COVID 19" },
  { clave: "diferencia_liquido", titulo: "DIFERENCIA LIQUIDO" },
  { clave: "anticipo_extraordinario", titulo: "ANTICIPO EXTRAORDINARIO" },
  { clave: "convenio_oftalm", titulo: "CONVENIO OFTALM. C.CH.C." },
  { clave: "feriado_progresivo", titulo: "FERIADO PROGRESIVO" },
  { clave: "operativo_oftalm", titulo: "OPERATIVO OFTALMOLOGICO" },
  { clave: "descuento_equipo", titulo: "DESCUENTO EQUIPO" },
  { clave: "descuento_permiso_sindical", titulo: "DESCUENTO PERMISO SINDICAL" },
  { clave: "prestamo_ccaf_los_heroes", titulo: "PRÉSTAMO CCAF LOS HÉROES" },
  { clave: "bono_seguridad", titulo: "BONO INCENTIVO DE SEGURIDAD" },
  { clave: "bono_produccion_incentivo", titulo: "BONO INCENTIVO DE PRODUCCION" },
  { clave: "diferencia_gratificacion", titulo: "DIFERENCIA GRATIFICACION" },
  { clave: "operativo_dental", titulo: "OPERATIVO DENTAL" },
  { clave: "dcto_ptmo_fonasa", titulo: "DCTO. PTMO FONASA" },
  { clave: "bono_icd", titulo: "BONO ICD" },
  { clave: "bono_sabado", titulo: "BONO SABADO" },
  { clave: "bono_liquido", titulo: "BONO LIQUIDO" },
  { clave: "bono_liquido_2", titulo: "BONO LIQUIDO 2" },
  { clave: "tratero", titulo: "BONO TRATERO" },
  { clave: "descuento_programa_mujer", titulo: "DESCUENTO PROGRAMA MUJER" },
  { clave: "cantidad_horas_rxtras_j_44h_50_prociento", titulo: "CANTIDAD CANTIDAD HORAS EXTRA J44H", horas: true },
  { clave: "horas_rxtras_j_44h_50_prociento", titulo: "HORAS EXTRA 50 PORCIENTO J44H" },
  { clave: "cantidad_horas_extra_mi55", titulo: "CANTIDAD CANTIDAD HORAS EXTRA FESTIVO", horas: true },
  { clave: "horas_extra_mi55", titulo: "HORAS EXTRA 50 PORCIENTO FESTIVO" },
  { clave: "bono_excelencia", titulo: "BONO EXCELENCIA" },
  { clave: "apt_colecta_ayuda", titulo: "APT. COLECTA AYUDA" },
  { clave: "descuento_colecta", titulo: "DESCUENTO COLECTA" },
  { clave: "bono_permanencia", titulo: "BONO PERMANENCIA" },
  { clave: "bono_incentivo_trimestral", titulo: "BONO INCENTIVO TRIMESTRAL" },
  { clave: "bono_mensual_reliq", titulo: "BONO MENSUAL RELIQ" },
  { clave: "rem_pago_exceso", titulo: "REM. PAGO EXCESO" },
  { clave: "bono_proyecto", titulo: "BONO PROYECTO" },
  { clave: "nombre_cuota_sindical", titulo: "NOMBRE CUOTA SINDICAL" },
  { clave: "contrib_empreador_pension", titulo: "CONTRIBUCION EMPREADOR PENSIÓN" },
  { clave: "comp_expectativa_vida", titulo: "COMP. EXPECTATIVA DE VIDA" },
];
